name: clone

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name ${{ github.actor }}
          git config remote.remote.url >&- || git remote add -f windows_hardening https://github.com/0x6d69636b/windows_hardening.git
      
      - name: add subtree windows_hardening
        run: |
          git subtree add --prefix=windows_hardening https://github.com/0x6d69636b/windows_hardening.git master
        continue-on-error: true 
        
      - name: push changes
        run: | 
          git push
        continue-on-error: true 
